---
abstract: 'Consume Paypal REST API via perl'
author:
  - 'Eduardo Almeida <eduardo at web2solutions.com.br>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.021, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: PaypalREST
version: '0.001'
